# Generated by Django 3.0.3 on 2022-12-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacname', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('Department', models.CharField(max_length=30)),
            ],
        ),
    ]
